"""📌 Récap — the charts that decide the most, and where each one lives.

Type: Feature
Uses: src/dashboard/content/recap_charts.py (generated from the graded chart review),
      src/dashboard/utils/navigation.goto
Triggers: app routing (`recap`)
Persists in: nothing

R271 (owner note L8 : « page récap des graphiques à plus forte valeur »). It does NOT
redraw them: the owner refuses the same number twice (notes L549), and a second copy of a
chart drifts from the first. It lists the ten best-graded charts of the review — decision,
confidence and relevance — as the question each one answers, with the button that opens
its page. The order is the review's, regenerated by `make recap`.
"""
import streamlit as st

from src.dashboard.content.recap_charts import RECAP
from src.dashboard.utils.i18n import t
from src.dashboard.utils.navigation import goto
from src.dashboard.utils.nav_sections import page_label


def show() -> None:
    st.title(t("recap.title", "📌 Récap — ce qui décide le plus"))
    st.caption(t("recap.intro",
                 "Les dix graphiques les mieux notés à la relecture, dans l'ordre : la "
                 "question à laquelle chacun répond, et la page qui le dessine."))
    for i, (question, page, _score) in enumerate(RECAP, start=1):
        left, right = st.columns([4, 1])
        left.markdown(f"**{i}. {question}**")
        if right.button(page_label(page), key=f"recap_{i}", width="stretch"):
            goto(page)


if __name__ == "__main__":
    show()
