"""GENERATED by tools/dev/build_chart_decisions.py from the charts review — do not
edit: change `decision` / `decision_en` in tools/dev/charts_dossier/review.yaml and
run `make chart-decisions`. R314: what each chart lets you decide."""

DECISIONS: dict[str, tuple[str, str]] = {
    'utils/campaign_compare.py::_render_track_funnel#1': (
        'Choisir le titre qui transforme le mieux de la pub au clic, pour y mettre le budget.',
        'Choose the track that converts best from ad to click, to put the budget there.'),
    'utils/campaign_pair.py::render_day0#1': (
        'Comparer deux campagnes à âge égal (J0 = premier euro), pour décider laquelle refaire.',
        'Compare two campaigns at equal age (day 0 = first euro), to decide which one to run again.'),
    'utils/campaign_pair.py::render_share_pair#1': (
        'Voir si deux campagnes ont touché le même public, en part de leur propre total, pour choisir quel ciblage garder.',
        'See whether two campaigns reached the same audience, as a share of their own total, to choose which targeting to keep.'),
    'utils/ml_widgets.py::render_classification_scorecard#1': (
        'Savoir à quel point te fier au modèle avant de lancer une campagne sur sa probabilité.',
        'Know how far to trust the model before launching a campaign on its probability.'),
    'utils/ml_widgets.py::render_lever_sensitivity#1': (
        'Voir si pousser ce levier fait monter ta probabilité, pour choisir ce que ta campagne doit viser.',
        'See whether pushing this lever raises your probability, to choose what your campaign should target.'),
    'utils/platform_chart.py::render_platform_chart#1': (
        'Voir si une sortie ou une campagne a fait monter tes écoutes sur toutes les plateformes, pour savoir où remettre du budget.',
        'See whether a release or a campaign lifted your streams across platforms, to know where to put budget back.'),
    'utils/s4a_entry_insight.py::render_prediction_vs_reality#1': (
        "Vérifier si la prédiction d'hier s'est confirmée, pour ajuster ta confiance avant la prochaine campagne.",
        "Check whether yesterday's prediction came true, to adjust your trust before the next campaign."),
    'views/admin.py::_render_costs#1': (
        "Comparer les coûts d'exploitation aux abonnements, pour savoir quel budget marketing l'app peut porter.",
        'Compare running costs with subscriptions, to know which marketing budget the app can carry.'),
    'views/airflow_kpi.py::show#1': (
        'Vérifier que les collectes tournent, pour que les chiffres de tes campagnes soient frais.',
        'Check that collections run, so your campaign figures are fresh.'),
    'views/airflow_kpi.py::show#2': (
        "Repérer une collecte qui ralentit, avant qu'elle ne retarde les chiffres de tes campagnes.",
        'Spot a slowing collection before it delays your campaign figures.'),
    'views/airflow_kpi.py::show#3': (
        'Voir quelles collectes échouent, pour savoir quels chiffres de campagne ne sont pas à jour.',
        'See which collections fail, to know which campaign figures are out of date.'),
    'views/alerts.py::_section_plan_evolution#1': (
        "Suivre combien d'artistes s'inscrivent et paient, pour juger tes campagnes d'acquisition.",
        'Follow how many artists sign up and pay, to judge your acquisition campaigns.'),
    'views/apple_music.py::_render_song_series#1': (
        "Voir si un titre gagne encore Apple et Shazam, signe qu'une campagne peut encore le porter.",
        'See whether a track still gains Apple and Shazam plays, a sign a campaign can still carry it.'),
    'views/apple_music.py::render_shazam_launches#1': (
        'Comparer deux sorties au même âge pour savoir si la dernière démarre mieux, et donc si sa promo marche.',
        'Compare two releases at the same age to tell whether the latest starts faster, and so whether its promo works.'),
    'views/apple_music.py::show#1': (
        'Identifier les titres qui portent Apple Music et Shazam, pour y orienter tes campagnes hors Spotify.',
        'Identify the tracks carrying Apple Music and Shazam, to aim your non-Spotify campaigns at them.'),
    'views/db_health.py::_show_ingestion_gaps#1': (
        'Vérifier que les données arrivent chaque jour, sinon ne pas juger une campagne sur des chiffres incomplets.',
        'Check that data lands every day, otherwise do not judge a campaign on incomplete figures.'),
    'views/etl_logs.py::_section_trend#1': (
        'Repérer une collecte en panne, avant de juger une campagne sur des chiffres qui manquent.',
        'Spot a broken collection before judging a campaign on missing figures.'),
    'views/home_tiles.py::_render_total_and_share#1': (
        'Voir quelle plateforme porte tes écoutes, pour savoir où concentrer ta promo.',
        'See which platform carries your streams, to know where to focus your promotion.'),
    'views/hypeddit.py::_render_campaign_series#1': (
        "Juger si ton smart link convertit les visites en clics vers les plateformes, et combien de pub l'a nourri.",
        'Judge whether your smart link turns visits into platform clicks, and how much ad spend fed it.'),
    'views/hypeddit.py::_render_campaign_series#2': (
        'Comparer tes dernières sorties en volumes — visites, clics, pub Meta autour de la sortie — pour savoir laquelle a vraiment porté.',
        'Compare your latest releases by volume — visits, clicks, Meta ads around the release — to see which one really carried.'),
    'views/imusician.py::_render_evolution#1': (
        "Voir si tes ventes montent ou retombent d'un mois à l'autre, pour juger l'effet de ta dernière sortie sur tes revenus.",
        'See whether your sales rise or fall month to month, to judge what your latest release did to your revenue.'),
    'views/imusician.py::render_break_even#1': (
        'Voir où en est ta trésorerie, ventes contre dépenses, pour fixer le budget de ta prochaine campagne.',
        "See where your cash stands, sales against spend, to set your next campaign's budget."),
    'views/instagram.py::_render_community#1': (
        'Suivre ta communauté Instagram pour savoir si tes campagnes la font grandir.',
        'Track your Instagram community to know whether your campaigns grow it.'),
    'views/instagram.py::render#1': (
        'Voir quels mois de publication ont le plus engagé, pour décider quoi publier et booster.',
        'See which publishing months engaged most, to decide what to post and boost.'),
    'views/meta_ads_overview.py::_render_campaign_waves#1': (
        "Savoir ce que chaque vague de pub a rapporté en écoutes et le prix d'une écoute, pour décider de relancer.",
        'Know what each ad wave brought in streams and the price per stream, to decide whether to relaunch.'),
    'views/meta_ads_overview.py::_render_campaign_waves#2': (
        "Voir combien de temps l'effet d'une vague dure, pour savoir quand juger une campagne et quand relancer.",
        "See how long a wave's effect lasts, to know when to judge a campaign and when to relaunch."),
    'views/meta_ads_overview.py::_render_global_perf#1': (
        'Comparer ce que chaque campagne a coûté et rapporté, pour choisir laquelle refaire.',
        'Compare what each campaign cost and delivered, to choose which one to run again.'),
    'views/meta_ads_overview.py::_show_meta_ads#1': (
        'Suivre au jour le jour si la dépense produit des clics à bon prix, pour couper ou pousser une campagne.',
        'Follow day by day whether spend buys clicks at a good price, to cut or push a campaign.'),
    'views/meta_ads_overview.py::_show_meta_ads#2': (
        "Choisir l'objectif d'optimisation Meta qui coûte le moins cher par résultat.",
        'Choose the Meta optimisation goal with the lowest cost per result.'),
    'views/meta_breakdowns.py::_render_engagement#1': (
        'Voir où ta pub fait réagir, pour cibler les audiences qui engagent.',
        'See where your ads get reactions, to target the audiences that engage.'),
    'views/meta_breakdowns.py::_render_engagement#2': (
        'Repérer sur la carte les pays qui réagissent, pour y concentrer le budget.',
        'Spot on the map the countries that react, to concentrate budget there.'),
    'views/meta_breakdowns.py::_render_performance#1': (
        "Choisir les pays, placements et âges où l'euro rend le clic le moins cher, pour recibler.",
        'Choose the countries, placements and ages where each euro buys the cheapest click, to retarget.'),
    'views/meta_breakdowns.py::_render_performance#2': (
        'Voir où ta pub a dépensé dans le monde, pour couper les pays qui coûtent sans rendre.',
        'See where your ads spent worldwide, to cut countries that cost without returning.'),
    'views/meta_creatives.py::_render_activity#1': (
        'Voir quelle créa a tourné quand, pour relier tes résultats à la bonne créa.',
        'See which creative ran when, to tie your results to the right creative.'),
    'views/meta_creatives.py::_render_creative_timeline#1': (
        'Voir combien de temps une créa reste rentable, pour savoir quand la remplacer.',
        'See how long a creative stays profitable, to know when to replace it.'),
    'views/meta_creatives.py::_render_fatigue#1': (
        "Détecter la fatigue de l'audience (fréquence qui monte, CTR qui baisse), pour renouveler la créa.",
        'Detect audience fatigue (rising frequency, falling CTR), to refresh the creative.'),
    'views/meta_creatives.py::_render_funnel#1': (
        "Voir à quelle étape les gens décrochent, pour corriger la créa ou la page d'arrivée.",
        'See at which step people drop off, to fix the creative or the landing page.'),
    'views/meta_creatives.py::_render_hooks#1': (
        'Savoir si une accroche (hook) fait baisser le coût, pour décider comment monter tes prochaines vidéos.',
        'Know whether a hook lowers cost, to decide how to cut your next videos.'),
    'views/meta_creatives.py::_render_ranking#1': (
        'Classer tes créas par coût et engagement, pour couper les chères et remettre du budget sur les bonnes.',
        'Rank your creatives by cost and engagement, to cut the expensive ones and fund the good ones.'),
    'views/meta_creatives.py::_render_scatter#1': (
        "Repérer d'un coup d'œil les créas qui dépensent beaucoup pour un coût élevé, à couper.",
        'Spot at a glance the creatives spending a lot at a high cost, to cut.'),
    'views/meta_x_spotify.py::_render_chart#1': (
        'Voir si budget, clics et écoutes bougent ensemble pendant la campagne, pour juger son effet.',
        'See whether budget, clicks and streams move together during the campaign, to judge its effect.'),
    'views/meta_x_spotify.py::_render_funnel#1': (
        "Voir où les gens se perdent de la pub à l'écoute, pour corriger le maillon faible.",
        'See where people get lost from ad to stream, to fix the weak link.'),
    'views/meta_x_spotify.py::_render_listener_verdict#1': (
        'Savoir si ta dernière pub a amené des auditeurs, pour décider de la reconduire.',
        'Know whether your last ad brought listeners, to decide whether to renew it.'),
    'views/meta_x_spotify.py::render_countries#1': (
        "Choisir les pays où l'euro de pub rapporte le plus d'écoutes, pour y cibler.",
        'Choose the countries where each ad euro brings the most streams, to target them.'),
    'views/onboarding.py::platform': (
        "Poser ton point de départ toutes plateformes, pour mesurer l'effet de tes prochaines campagnes.",
        'Set your all-platform starting point, to measure the effect of your next campaigns.'),
    'views/revenue_forecast.py::_render_trigger_value#1': (
        "Chiffrer ce que vaut un déclenchement d'algorithme, pour savoir combien dépenser pour l'obtenir.",
        'Put a value on an algorithm trigger, to know how much to spend to get it.'),
    'views/revenue_forecast.py::_tab_ltv#1': (
        "Savoir combien vaut un abonné, pour fixer ce qu'une campagne d'acquisition peut coûter par artiste.",
        'Know what a subscriber is worth, to set what an acquisition campaign may cost per artist.'),
    'views/sacem.py::render_section#1': (
        "Voir ce que les retenues prennent sur tes royalties SACEM, pour prévoir le net réel d'une répartition.",
        'See what deductions take from your SACEM royalties, to plan the real net of a distribution.'),
    'views/soundcloud.py::_render_age_comparison#1': (
        'Comparer tes titres au même âge, pour savoir lequel continue de gagner et mérite une relance.',
        'Compare your tracks at the same age, to know which one keeps gaining and deserves a push.'),
    'views/soundcloud.py::_render_catalog_series#1': (
        "Savoir si écoutes et engagement SoundCloud progressent ensemble, pour décider d'y investir du temps promo.",
        'Know whether SoundCloud plays and engagement grow together, to decide whether to invest promo time there.'),
    'views/soundcloud.py::show#1': (
        'Choisir les titres SoundCloud qui engagent le plus, à mettre en avant dans tes campagnes.',
        'Pick the SoundCloud tracks that engage most, to feature in your campaigns.'),
    'views/spotify_s4a_combined.py::_render_momentum#1': (
        'Repérer le titre qui prend en ce moment, pour choisir lequel promouvoir en priorité.',
        'Spot the track that is taking off right now, to choose which one to promote first.'),
    'views/spotify_s4a_combined.py::_render_secondary#1': (
        'Savoir si un titre vit encore et si ton audience suit, pour décider de relancer sa promo ou de passer au suivant.',
        'Know whether a track is still alive and your audience follows, to decide whether to relaunch its promo or move on.'),
    'views/spotify_s4a_combined.py::render_release_cohort#1': (
        'Comparer ta dernière sortie aux précédentes au même âge, pour décider si elle mérite un coup de pub maintenant.',
        'Compare your latest release with the previous ones at the same age, to decide whether it deserves an ad push now.'),
    'views/trigger_algo/_common/_budget_roi.py::_show_meta_lever_scoring#1': (
        'Repérer la campagne au meilleur CPR, pour y remettre le budget de la prochaine sortie.',
        "Spot the campaign with the best CPR, to put the next release's budget back on it."),
    'views/trigger_algo/_playlist_detail.py::render_ce_qui_pese#1': (
        'Voir, pour chaque playlist, le critère qui retient le plus ton titre, pour savoir quoi travailler en premier.',
        'See, for each playlist, the criterion holding your track back the most, to know what to work on first.'),
    'views/trigger_algo/_playlist_detail.py::render_ce_qui_pese#2': (
        "Voir quel seuil est le plus loin d'être atteint, pour savoir où mettre l'effort en premier.",
        'See which threshold is furthest from being met, to know where to put the effort first.'),
    'views/trigger_algo/_tab_algo_streams.py::_render_estimates#1': (
        "Estimer ce qu'un déclenchement d'algorithme rapporte, pour chiffrer le budget qui vaut la peine.",
        'Estimate what an algorithm trigger brings, to size the budget worth spending.'),
    'views/trigger_algo/_tab_algo_streams.py::_show_tab_algo_streams#1': (
        "Voir combien d'écoutes chaque algorithme t'apporte, pour savoir lequel viser en campagne.",
        'See how many streams each algorithm brings you, to know which one to aim for.'),
    'views/trigger_algo/_tab_budget_roi.py::_render_breakeven#1': (
        'Savoir quand la pub sera remboursée, pour décider combien investir sur un titre.',
        'Know when the ads will have paid back, to decide how much to invest in a track.'),
    'views/trigger_algo/_tab_budget_roi.py::_render_fit#1': (
        "Savoir si tes revenus suivent ta dépense Meta, pour décider d'augmenter ou de baisser le budget.",
        'Know whether your revenue follows your Meta spend, to decide whether to raise or cut the budget.'),
    'views/trigger_algo/_tab_budget_roi.py::_show_tab_budget_roi#1': (
        'Voir ce qui reste de ton budget Meta, pour savoir combien de semaines de campagne il te reste.',
        'See what is left of your Meta budget, to know how many weeks of campaign remain.'),
    'views/trigger_algo/_tab_catalogue.py::_show_tab_catalogue#1': (
        'Voir quel titre est le plus proche de déclencher un algorithme, pour y concentrer ta prochaine campagne.',
        'See which track is closest to triggering an algorithm, to focus your next campaign on it.'),
    'views/trigger_algo/_tab_catalogue.py::_show_tab_catalogue#2': (
        "Savoir quelle valeur de chaque levier viser, pour fixer l'objectif de ta campagne.",
        "Know which value of each lever to aim for, to set your campaign's goal."),
    'views/trigger_algo/_tab_explainability.py::_show_tab_explainability#1': (
        'Voir quels leviers poussent la prédiction, pour savoir lequel ta campagne doit faire bouger.',
        'See which levers drive the prediction, to know which one your campaign must move.'),
    'views/trigger_algo/_tab_explainability.py::_show_tab_explainability#2': (
        "Voir le détail de l'effet de chaque levier, pour prioriser celui que ta pub peut influencer.",
        "See each lever's effect in detail, to prioritise the one your ads can influence."),
    'views/trigger_algo/_tab_explainability.py::_show_tab_explainability#3': (
        "Voir comment un levier change la prédiction, pour fixer l'effort de campagne utile.",
        'See how a lever changes the prediction, to set the useful campaign effort.'),
    'views/trigger_algo/_tab_lifecycle.py::_show_tab_lifecycle#1': (
        'Voir si ton titre suit la courbe de vie habituelle, pour choisir le bon moment de promo.',
        'See whether your track follows the usual life curve, to pick the right time to promote.'),
    'views/trigger_algo/_tab_model.py::_show_error_by_prediction_week#1': (
        "Voir si le modèle s'améliore semaine après semaine, avant de lui confier une décision de campagne.",
        'See whether the model improves week after week, before trusting it with a campaign decision.'),
    'views/trigger_algo/_tab_model.py::_show_volume_vs_recorded#1': (
        'Vérifier si le volume prédit colle au réel, pour savoir si tu peux budgéter une campagne dessus.',
        'Check whether the predicted volume matches reality, to know if you can budget a campaign on it.'),
    'views/trigger_algo/_tab_reglages.py::_budget_declenchement#1': (
        "Voir l'ordre de grandeur du budget par playlist, pour choisir laquelle viser avec ta campagne.",
        'See the rough budget per playlist, to choose which one your campaign should aim for.'),
    'views/trigger_algo/_tab_reglages.py::_rendre_axe#1': (
        'Savoir quel réglage garder sur ta prochaine campagne : le vert est celui qui coûte le moins par clic.',
        'Know which setting to keep on your next campaign: green is the one with the lowest cost per click.'),
    'views/trigger_algo/_tab_titre.py::_render_pareto#1': (
        "Voir le levier qui comble le plus de l'écart, pour décider où mettre le budget Meta en premier.",
        'See the lever that closes most of the gap, to decide where to put the Meta budget first.'),
    'views/usage_analytics.py::show#1': (
        "Voir si l'app est utilisée jour après jour, pour mesurer l'effet d'une campagne d'acquisition.",
        'See whether the app is used day after day, to measure the effect of an acquisition campaign.'),
    'views/youtube.py::_channel_section#1': (
        "Juger si ta chaîne YouTube gagne vues et abonnés, pour décider d'y lancer une campagne vidéo.",
        'Judge whether your YouTube channel gains views and subscribers, to decide whether to run a video campaign.'),
    'views/youtube.py::_channel_section#2': (
        'Voir quelles vidéos ont pris des vues sur la période, pour savoir lesquelles relancer ou mettre en avant.',
        'See which videos gained views over the period, to know which ones to push again.'),
    'views/youtube.py::_videos_section#1': (
        "Voir d'un coup d'œil quelles vidéos font le plus de vues et lesquelles plaisent, pour choisir celle à promouvoir.",
        'See at a glance which videos get the most views and which are liked, to pick the one to promote.'),
    'views/youtube.py::_videos_section#2': (
        'Savoir si tes vues tiennent à deux ou trois vidéos ou shorts, pour décider entre relancer un format qui marche et diversifier.',
        'Know whether your views rest on two or three videos or shorts, to choose between pushing a winning format and diversifying.'),
    'views/youtube.py::_videos_section#3': (
        'Repérer les vidéos qui prennent encore des vues ce mois-ci, pour mettre en avant celles qui vivent encore.',
        'Spot the videos still drawing views this month, to promote the ones that are still alive.'),
}
