"""GENERATED by tools/dev/build_recap.py from the graded chart review — do not edit.

Type: Utility
Uses: nothing (data)
Triggers: views/recap.py
Persists in: nothing
"""

# (the decision the chart answers, the page that draws it, review score /15)
RECAP: tuple[tuple[str, str, int], ...] = (
    ("Ma dernière pub m'a-t-elle amené des auditeurs ?", 'meta_x_spotify', 15),
    ('Ma dernière sortie fait-elle mieux que les précédentes au même âge ?', 'spotify_s4a_combined', 15),
    ('Au jour le jour, la dépense produit-elle des clics, à quel coût ?', 'meta_ads_overview', 13),
    ('Le titre choisi est-il encore écouté, encore vu par Spotify ; mon audience grandit-elle ?', 'spotify_s4a_combined', 13),
    ("Ma trésorerie — ventes, SACEM et dépenses, où j'en suis au total ?", 'imusician', 12),
    ('Ma communauté Instagram grandit-elle ?', 'instagram', 12),
    ("Combien de temps l'effet d'une vague de pub dure-t-il, donc quand la juger et quand relancer ?", 'meta_ads_overview', 12),
    ("Que m'a coûté et rapporté chaque campagne (dépense, impressions, clics, CPM, CPC, CPR) ?", 'meta_ads_overview', 12),
    ('Où ma pub a-t-elle dépensé, dans le monde ?', 'meta_breakdowns', 12),
    ('Les créas avec « hook » coûtent-elles moins cher que sans ?', 'meta_creatives', 12),
)
