"""Road to Algo — tab: realized streams generated by the algorithmic playlists.

Type: Sub
Uses: streamlit, plotly, pandas
Reads: s4a_song_algo_outcomes (manual capture, Saisie S4A)

Once a song has been picked up by Discover Weekly / Release Radar / Radio, this tab
answers "how many streams did each playlist actually generate?" — the realized payoff,
not the prediction. Shows the cumulative total AND each playlist's contribution, over the
chosen window (7d / 28d / custom).
"""
import plotly.express as px
import streamlit as st

from src.dashboard.utils.i18n import t

_ARTIST_FILTER = "%1x7xxxxxxx%"
_WINDOWS = [("7d", "7 jours"), ("28d", "28 jours"), ("custom", "Période perso")]
_SOURCE_LABELS = {"dw_streams": "Discover Weekly", "rr_streams": "Release Radar", "radio_streams": "Radio"}
_SOURCE_COLORS = {"Discover Weekly": "#1DB954", "Release Radar": "#F037A5", "Radio": "#FFA726"}


def _show_tab_algo_streams(db, song, artist_id):
    st.subheader(t("trigger_algo.algostreams_header",
                   "📈 Streams générés par les playlists algorithmiques"))
    st.caption(t("trigger_algo.algostreams_caption",
                 "Une fois un titre capté par les algos, combien de streams chaque playlist a "
                 "réellement généré. Saisie dans 📝 Saisie S4A. Le total = somme des 3 sources."))

    if not song:
        st.info(t("trigger_algo.algostreams_no_track", "Sélectionne un titre ci-dessus."))
        return
    if song.lower().find("1x7xxxxxxx") != -1:
        return

    win_labels = {code: lbl for code, lbl in _WINDOWS}
    window = st.radio(
        t("trigger_algo.algostreams_window", "Fenêtre"),
        [c for c, _ in _WINDOWS], horizontal=True,
        format_func=lambda c: win_labels[c], key=f"algostreams_win_{artist_id}",
    )

    df = db.fetch_df(
        """SELECT recorded_at, dw_streams, rr_streams, radio_streams
           FROM s4a_song_algo_outcomes
           WHERE artist_id = %s AND song = %s AND time_window = %s AND song NOT ILIKE %s
           ORDER BY recorded_at""",
        (artist_id, song, window, _ARTIST_FILTER),
    )
    if df is None or df.empty:
        st.info(t("trigger_algo.algostreams_empty",
                  "Aucune donnée pour ce titre sur cette fenêtre. Saisis les streams "
                  "DW/RR/Radio dans 📝 Saisie S4A."))
        return

    df["total"] = df["dw_streams"] + df["rr_streams"] + df["radio_streams"]
    latest = df.iloc[-1]

    # KPI cards: latest per-playlist + cumulative total.
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("🟢 Discover Weekly", int(latest["dw_streams"]))
    c2.metric("🩷 Release Radar", int(latest["rr_streams"]))
    c3.metric("🟠 Radio", int(latest["radio_streams"]))
    c4.metric(t("trigger_algo.algostreams_total", "Σ Total (cumulé)"), int(latest["total"]))

    # Stacked bar: stack height = cumulative total, each segment = one playlist's streams.
    long = df.melt(id_vars="recorded_at",
                   value_vars=["dw_streams", "rr_streams", "radio_streams"],
                   var_name="source", value_name="streams")
    long["source"] = long["source"].map(_SOURCE_LABELS)
    fig = px.bar(
        long, x="recorded_at", y="streams", color="source", barmode="stack",
        color_discrete_map=_SOURCE_COLORS,
        labels={"recorded_at": "", "streams": t("trigger_algo.algostreams_y", "Streams"),
                "source": t("trigger_algo.algostreams_source", "Playlist")},
    )
    fig.update_layout(hovermode="x unified", legend_title_text="")
    st.plotly_chart(fig, width="stretch")

    with st.expander(t("trigger_algo.algostreams_table", "📋 Détail chiffré")):
        show = df.rename(columns={"recorded_at": "Date", **_SOURCE_LABELS, "total": "Total"})
        st.dataframe(show, hide_index=True, width="stretch")
