"""Road to Algo — tab: realized streams generated by the algorithmic playlists.

Type: Sub
Uses: streamlit, plotly, pandas
Reads: s4a_song_algo_outcomes (manual capture, Saisie S4A)

Once a song has been picked up by Discover Weekly / Release Radar / Radio, this tab
answers "how many streams did each playlist actually generate?" — the realized payoff,
not the prediction. Shows the cumulative total AND each playlist's contribution, over the
chosen window (7d / 28d / custom).
"""
import textwrap
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

from src.dashboard.utils.date_format import format_date
from src.dashboard.utils.i18n import t
from src.dashboard.utils.platform_colors import ALGO_COLORS

from src.utils.artist_name_filter import (
    ARTIST_NAME_LIKE as _ARTIST_FILTER,
)
from src.dashboard.utils import charts
from src.dashboard.utils.ui import secondary_analyses
from src.utils.algo_order import ALGO_ORDER
_WINDOWS = [("7d", "7 jours"), ("28d", "28 jours"), ("custom", "Période perso")]
_SOURCE_LABELS = {"dw_streams": "Discover Weekly", "rr_streams": "Release Radar", "radio_streams": "Radio"}
_SOURCE_COLORS = {"Discover Weekly": ALGO_COLORS["DW"], "Release Radar": ALGO_COLORS["RR"],
                  "Radio": ALGO_COLORS["RADIO"]}   # R260 — the one algorithm palette


def _show_tab_algo_streams(db, song, artist_id):
    st.subheader(t("trigger_algo.algostreams_header",
                   "📈 Streams générés par les playlists algorithmiques"))
    _render_estimates()   # R247 (fiche 43) — visible même sans aucune saisie
    if not song:
        st.info(t("trigger_algo.algostreams_no_track", "Sélectionne un titre ci-dessus."))
        return
    if song.lower().find("1x7xxxxxxx") != -1:
        return

    win_labels = {code: lbl for code, lbl in _WINDOWS}
    window = st.radio(
        t("trigger_algo.algostreams_window", "Fenêtre"),
        [c for c, _ in _WINDOWS], horizontal=True,
        format_func=lambda c: win_labels[c], key=f"algostreams_win_{artist_id}",
    )

    df = db.fetch_df(
        """SELECT recorded_at, dw_streams, rr_streams, radio_streams
           FROM s4a_song_algo_outcomes
           WHERE artist_id = %s AND song = %s AND time_window = %s AND song NOT ILIKE %s
           ORDER BY recorded_at""",
        (artist_id, song, window, _ARTIST_FILTER),
    )
    if df is None or df.empty:
        st.info(t("trigger_algo.algostreams_empty",
                  "Aucune donnée pour ce titre sur cette fenêtre. Saisis les streams "
                  "DW/RR/Radio dans 📝 Saisie S4A."))
        return

    df["total"] = df["dw_streams"] + df["rr_streams"] + df["radio_streams"]
    latest = df.iloc[-1]

    # KPI cards: latest per-playlist + cumulative total.
    # DW → Radio → RR, the one order (`ALGO_ORDER`, R380) — one tile per call, so the
    # gold-coverage scan can attribute each to its column.
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("🟢 Discover Weekly", int(latest["dw_streams"]))
    c2.metric("🟠 Radio", int(latest["radio_streams"]))
    c3.metric("🩷 Release Radar", int(latest["rr_streams"]))
    c4.metric(t("trigger_algo.algostreams_total", "Σ Total (cumulé)"), int(latest["total"]))

    # Stacked bar: stack height = cumulative total, each segment = one playlist's streams.
    long = df.melt(id_vars="recorded_at",
                   value_vars=[f"{a.lower()}_streams" for a in ALGO_ORDER],
                   var_name="source", value_name="streams")
    long["source"] = long["source"].map(_SOURCE_LABELS)
    # R209 (2026-09-27) — the readings are SNAPSHOTS, often one or two: on a date axis a
    # bar is one millisecond wide, invisible, and the axis collapsed to « 23:59:59,9996 →
    # 00:00:00,0004 » (seen in the dossier). Each reading is a CATEGORY, labelled by its
    # day: its bar has a width, and the order stays the time order.
    long["recorded_at"] = [format_date(d) for d in pd.to_datetime(long["recorded_at"])]
    fig = px.bar(
        long, x="recorded_at", y="streams", color="source", barmode="stack",
        color_discrete_map=_SOURCE_COLORS,
        labels={"recorded_at": "", "streams": t("trigger_algo.algostreams_y", "Streams"),
                "source": t("trigger_algo.algostreams_source", "Playlist")},
    )
    fig.update_layout(hovermode="x unified", legend_title_text="")
    fig.update_xaxes(type="category")
    # R247 : l'historique des saisies se replie — l'estimation (fiche 43) est la réponse
    # que le propriétaire demandait ; les quatre tuiles au-dessus portent déjà le dernier relevé.
    with secondary_analyses(t("trigger_algo.algostreams_history", "📊 Historique de tes saisies")):
        charts.plotly_chart(fig, width="stretch")



# ── R247 (fiche 43) — what an algorithm usually brings once it has triggered ──────────
_ESTIMATES = (Path(__file__).resolve().parents[4]
              / "machine_learning" / "models" / "v3" / "algo_stream_estimates.json")
_AGE_LABELS = {"j28": "Le 1er mois", "m6": "Vers 6 mois", "y1": "Vers 1 an"}
_ALGO_LABELS = {"dw": "Discover Weekly", "rr": "Release Radar", "radio": "Radio"}


def load_estimates() -> dict:
    """The exported estimates, or {} when the artefact is absent. Pure on the file.

    No `path=` parameter: the gold-coverage map cannot resolve a default argument at the
    call site, and filed this figure « indéterminée » instead of « hors base »."""
    import json
    try:
        return json.loads(_ESTIMATES.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def estimates_figure(est: dict):
    """One panel per algorithm, on its OWN scale (Radio at 6 months runs to 22 490 and
    flattened the rest on a shared axis): median bar + P25–P75 whisker per age, and a
    refused cell WRITTEN in its place — an empty bar carries no text (render, 2026-09-27)."""
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
    algos = list((est.get("estimates") or {}).items())
    fig = make_subplots(rows=1, cols=max(len(algos), 1), horizontal_spacing=0.08,
                        subplot_titles=[_ALGO_LABELS.get(a, a) for a, _ in algos])
    for i, (algo, ages) in enumerate(algos, start=1):
        xs = [t(f"trigger_algo.est_age.{age}", _AGE_LABELS[age]) for age in ages]
        cells = list(ages.values())
        fig.add_trace(go.Bar(
            x=xs, y=[None if c.get("refused") else c["p50"] for c in cells],
            text=[None if c.get("refused") else
                  f"{c['p50']:,.0f}<br>({c['p25']:,.0f}–{c['p75']:,.0f})".replace(",", " ")
                  for c in cells],
            textposition="outside", cliponaxis=False, showlegend=False,
            marker_color=_SOURCE_COLORS.get(_ALGO_LABELS.get(algo)),
            error_y=dict(type="data", symmetric=False,
                         array=[None if c.get("refused") else c["p75"] - c["p50"] for c in cells],
                         arrayminus=[None if c.get("refused") else c["p50"] - c["p25"] for c in cells])),
            row=1, col=i)
        for x, c in zip(xs, cells):
            if c.get("refused"):
                fig.add_annotation(x=x, y=0, row=1, col=i,
                                   yanchor="bottom", showarrow=False, font=dict(size=10, color="#888"),
                                   text="<br>".join(textwrap.wrap(
                                       t("trigger_algo.est_refused", "pas assez de titres ({n})")
                                       .format(n=c["n"]), 12)))
    fig.update_layout(height=380, margin=dict(t=50))
    fig.update_yaxes(rangemode="tozero")
    fig.update_yaxes(title_text=t("trigger_algo.est_axis", "Streams de l'algorithme sur 28 jours"),
                     row=1, col=1)
    return fig


def _render_estimates() -> None:
    est = load_estimates()
    if not est.get("estimates"):
        return
    st.markdown(t("trigger_algo.est_head",
                  "**Si l'algorithme se déclenche, ce qu'il rapporte d'habitude** — estimation "
                  "sur les {n} titres du jeu d'entraînement, pas une prévision pour ton titre."
                  ).format(n=est.get("rows", "?")))
    charts.plotly_chart(estimates_figure(est), width="stretch")
    st.caption(t("trigger_algo.est_caption",
                 "Barre = la médiane, trait = de P25 à P75 (la moitié des titres déclenchés est "
                 "dans cette fourchette). Ce sont des streams PAR MOIS À CET ÂGE, chez des titres "
                 "qui avaient déclenché — pas un total cumulé. « Pas assez de titres » : moins de "
                 "{m} titres déclenchés de cet âge dans le jeu, donc aucun chiffre."
                 ).format(m=est.get("min_n", 10)))
