-- Migration 022: per-song playlist add count entered manually from the S4A UI.
-- Streams generated by playlists are not available in CSV exports — this table
-- stores the count of playlists a given song was added to over a specific period,
-- entered manually by the user.

CREATE TABLE IF NOT EXISTS s4a_song_playlist_adds (
    artist_id    INTEGER NOT NULL,
    song         TEXT NOT NULL,
    period_start DATE NOT NULL,
    period_end   DATE NOT NULL,
    count        INTEGER NOT NULL DEFAULT 0,
    collected_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (artist_id, song, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_s4a_song_playlist_adds_artist_song
    ON s4a_song_playlist_adds (artist_id, song);
