#!/usr/bin/env python3
"""Generate src/dashboard/content/chart_decisions.py — what each chart lets the artist decide.

Type: Utility
Uses: tools/dev/charts_dossier/review.yaml (`decision`, `decision_en` of each app chart)
Triggers: `make chart-decisions` ; tests/test_every_chart_says_what_it_lets_you_decide.py
Persists in: src/dashboard/content/chart_decisions.py (generated, committed)

R314 (owner, 2026-09-28 — « une de mes exigences clés ») : under EVERY app chart, one line
saying what it lets you decide in managing your marketing campaigns. ONE source — the review
the owner validates in the PDF — and the dashboard reads a generated module, because its
container does not carry tools/ (same pattern as `build_recap.py`).

OVERRIDES carry the lines of a chart drawn by a shared helper on several pages, where each
page says something different (`render_platform_chart`: home and onboarding) — code-critic.

    python3 tools/dev/build_chart_decisions.py [--check]
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src" / "dashboard" / "content" / "chart_decisions.py"
REVIEW = ROOT / "tools" / "dev" / "charts_dossier" / "review.yaml"

#: key passed as `decision_key=` by a page → (fr, en).
OVERRIDES: dict[str, tuple[str, str]] = {
    "views/home.py::platform": (
        "Voir si une sortie ou une campagne a fait monter tes écoutes sur toutes les "
        "plateformes, pour savoir où remettre du budget.",
        "See whether a release or a campaign lifted your streams across platforms, to know "
        "where to put budget back."),
    "views/onboarding.py::platform": (
        "Poser ton point de départ toutes plateformes, pour mesurer l'effet de tes prochaines "
        "campagnes.",
        "Set your all-platform starting point, to measure the effect of your next campaigns."),
}


def decisions(review: dict) -> dict[str, tuple[str, str]]:
    """{key without the `src/dashboard/` prefix: (fr, en)} of every app chart. Pure."""
    out = {k[len("src/dashboard/"):]: (r["decision"], r.get("decision_en") or r["decision"])
           for k, r in review.items()
           if k.startswith("src/dashboard/") and r.get("decision")}
    out.update(OVERRIDES)
    return dict(sorted(out.items()))


def render(dec: dict[str, tuple[str, str]]) -> str:
    lines = ['"""GENERATED by tools/dev/build_chart_decisions.py from the charts review — do not',
             "edit: change `decision` / `decision_en` in tools/dev/charts_dossier/review.yaml and",
             'run `make chart-decisions`. R314: what each chart lets you decide."""',
             "", "DECISIONS: dict[str, tuple[str, str]] = {"]
    for k, (fr, en) in dec.items():
        lines += [f"    {k!r}: (", f"        {fr!r},", f"        {en!r}),"]
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    text = render(decisions(yaml.safe_load(REVIEW.read_text(encoding="utf-8"))))
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("❌ chart_decisions.py is stale — run: make chart-decisions", file=sys.stderr)
            return 1
        print("✅ chart_decisions.py describes the review")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"écrit : {OUT.relative_to(ROOT)} ({len(text.splitlines())} lignes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
