#!/usr/bin/env python3
"""Generate src/dashboard/content/recap_charts.py — the charts that decide the most.

Type: Utility
Uses: tools/dev/charts_dossier/review.yaml (the graded review), src/dashboard/routes.py
Triggers: `make recap` ; tests/test_the_recap_page_is_the_reviews_top.py (staleness)
Persists in: src/dashboard/content/recap_charts.py (generated, committed)

R271 (owner note L8 : « page récap des graphiques à plus forte valeur »). The owner also
refuses redundancy (notes L549), so the recap does NOT redraw a chart: it lists the
highest-graded ones — decision + confidence + relevance, kept in the review — each with
its question and the page that draws it. The ranking is the review's, never re-judged here.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "src" / "dashboard" / "content" / "recap_charts.py"
TOP = 10
_ROLES = ("meta", "plateforme", "prediction", "business")


def ranked(review: dict, routes: dict) -> list[tuple[str, str, int]]:
    """[(question, page key, score)] of the kept, routed charts, best first. Pure."""
    by_module: dict[str, str] = {}
    for page, module in routes.items():
        by_module.setdefault(module.split(".", 1)[1], page)
    rows, seen = [], set()
    for key, v in review.items():
        if not isinstance(v, dict) or v.get("v") != "garder" or v.get("role") not in _ROLES:
            continue
        path = key.split("::")[0]
        if "src/dashboard/views/" not in path:
            continue
        module = path.split("src/dashboard/views/")[1].removesuffix(".py").split("/")[0]
        page = by_module.get(module)
        if not page or v["q"] in seen:
            continue
        seen.add(v["q"])
        # The review's question carries its own plumbing in a trailing parenthesis
        # (« (fusion R212 …) », « (carte, repliée) ») — written for the reviewer, never
        # for the artist the recap speaks to.
        question = re.sub(r"\s*\([^()]*\)\s*$", "", str(v["q"])).strip()
        score = int(v.get("d") or 0) + int(v.get("c") or 0) + int(v.get("p") or 0)
        rows.append((question, page, score, int(v.get("d") or 0)))
    rows.sort(key=lambda r: (-r[2], -r[3], r[1], r[0]))
    return [(q, p, s) for q, p, s, _d in rows[:TOP]]


def render(rows: list[tuple[str, str, int]]) -> str:
    body = "\n".join(f"    ({q!r}, {p!r}, {s})," for q, p, s in rows)
    return ('"""GENERATED by tools/dev/build_recap.py from the graded chart review — do not '
            'edit.\n\nType: Utility\nUses: nothing (data)\nTriggers: views/recap.py\n'
            'Persists in: nothing\n"""\n\n'
            f"# (the decision the chart answers, the page that draws it, review score /15)\n"
            f"RECAP: tuple[tuple[str, str, int], ...] = (\n{body}\n)\n")


def main() -> int:
    sys.path.insert(0, str(ROOT))
    from src.dashboard.routes import ROUTES
    review = yaml.safe_load((ROOT / "tools/dev/charts_dossier/review.yaml").read_text(encoding="utf-8"))
    text = render(ranked(review, ROUTES))
    if "--check" in sys.argv:
        if OUT.read_text(encoding="utf-8") != text:
            print("❌ recap_charts.py is stale — run: make recap", file=sys.stderr)
            return 1
        print("✅ recap_charts.py matches the review")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"écrit : {OUT.relative_to(ROOT)} ({text.count(chr(10))} lignes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
