#!/usr/bin/env python3
"""R509 — mutation of PRODUCT code, bounded to the pure parsers (study E1).

Type: Utility
Uses: mutmut 2.5 (dev extra), git archive
Triggers: `make mutate-parsers`, .github/workflows/mutation-weekly.yml
Persists in: .claude/dev-docs/mutation-survivors.md (generated, NOT versioned)

`tools/dev/mutate_guards.py` mutates GUARDS to prove they go red; this does the opposite —
it mutates `src/transformers/` and lists the mutants no test kills. Each survivor is a
behaviour of a parser that the suite does not pin.

Why mutmut 2 and not 3: mutmut 3 refuses a package NAMED `src` (« Module name starts with
`src.`, which is invalid », its trampoline) — this repo imports `src.transformers.*`
everywhere. mutmut 2 mutates in place, so it runs in a temporary COPY of the working tree:
the tree itself is never touched, and a killed run leaves nothing behind.

Keep-or-retire criterion, fixed before the first run: ≥1 survivor that is a real test gap
within the first month, else remove. Met on the trial run (2026-10-11): `_to_float` of a
blank SACEM cell mutated to 1.0 survived — a blank amount would have read 1 €.

Exit 0 whatever survives (survivors are a report, not a failure); 2 when a module's tests
are red WITHOUT mutation (the run measured nothing).
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / ".claude/dev-docs/mutation-survivors.md"
_MODULES = ROOT / "src/transformers"


def modules() -> list[str]:
    return sorted(p.stem for p in _MODULES.glob("*.py") if p.stem != "__init__")


def tests_for(module: str) -> list[str]:
    """The test files that import this module — the only ones that can kill its mutants."""
    needle = re.compile(rf"\bsrc\.transformers\.{module}\b|from src\.transformers import [^\n]*\b{module}\b")
    return sorted(str(p.relative_to(ROOT)) for p in (ROOT / "tests").glob("test_*.py")
                  if needle.search(p.read_text(encoding="utf-8")))


def _mutmut(copy: Path, *args: str, timeout: int = 3600) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, "-m", "mutmut", *args], cwd=copy,
                          capture_output=True, text=True, timeout=timeout)


def run_module(copy: Path, module: str) -> dict:
    tests = tests_for(module)
    if not tests:
        return {"module": module, "tests": [], "survivors": [], "error": "no test imports it"}
    (copy / ".mutmut-cache").unlink(missing_ok=True)
    runner = f"{sys.executable} -m pytest -q -x -p no:cacheprovider -p no:randomly {' '.join(tests)}"
    run = _mutmut(copy, "run", "--paths-to-mutate", f"src/transformers/{module}.py",
                  "--runner", runner, "--no-progress")
    if "Tests don't run cleanly without mutations" in run.stdout + run.stderr:
        return {"module": module, "tests": tests, "survivors": [], "error": "baseline red"}
    ids = _mutmut(copy, "result-ids", "survived").stdout.split()
    survivors = []
    for mid in ids:
        diff = _mutmut(copy, "show", mid).stdout
        lines = [ln for ln in diff.splitlines() if re.match(r"^[-+][^-+]", ln)]
        survivors.append((mid, lines))
    return {"module": module, "tests": tests, "survivors": survivors, "error": None}


def render(results: list[dict]) -> str:
    out = ["# Mutation survivors — `src/transformers/` (generated by `make mutate-parsers`)", "",
           "Not versioned. Each survivor is a parser behaviour no test pins. A real gap gets a",
           "test; an equivalent mutant (same behaviour) is ignored. See tools/dev/mutate_parsers.py.", "",
           "| module | tests | survivors |", "|---|---|---|"]
    for r in results:
        out.append(f"| {r['module']} | {len(r['tests'])} | {r['error'] or len(r['survivors'])} |")
    for r in results:
        if r["survivors"]:
            out += ["", f"## {r['module']}", ""]
            for mid, lines in r["survivors"]:
                out += [f"- mutant {mid}", "  ```diff", *[f"  {ln}" for ln in lines], "  ```"]
    return "\n".join(out) + "\n"


def _copy_worktree(copy: Path) -> None:
    """The WORKING TREE (tracked + new, not ignored) — a test written but not yet committed
    must count: the first version copied HEAD and reported 22 survivors after they were
    pinned. In CI the working tree is the checkout, so both read the same thing."""
    listed = subprocess.run(["git", "ls-files", "-co", "--exclude-standard", "-z"], cwd=ROOT,
                            capture_output=True, check=True).stdout.decode().split("\0")
    for rel in filter(None, listed):
        src = ROOT / rel
        if src.is_file():
            (copy / rel).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, copy / rel)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("modules", nargs="*", help=f"default: all of {', '.join(modules())}")
    args = ap.parse_args(argv)
    wanted = args.modules or modules()
    unknown = sorted(set(wanted) - set(modules()))
    if unknown:
        print(f"❌ unknown module(s): {unknown} — choose among {modules()}", file=sys.stderr)
        return 2
    copy = Path(tempfile.mkdtemp(prefix="mutate-parsers-"))
    try:
        _copy_worktree(copy)
        results = []
        for module in wanted:
            r = run_module(copy, module)
            results.append(r)
            print(f"{module:<24} {len(r['tests']):>2} test file(s)  "
                  f"{r['error'] or str(len(r['survivors'])) + ' survivor(s)'}", flush=True)
    finally:
        shutil.rmtree(copy, ignore_errors=True)
    REPORT.write_text(render(results), encoding="utf-8")
    print(f"report: {REPORT.relative_to(ROOT)}")
    return 2 if any(r["error"] == "baseline red" for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
