"""EN catalog for the trigger_algo (Road to Algo / ML) view package."""

EN = {
    # router.py — page-level
    "trigger_algo.title": "🚀 Road to Algorithms (J+28)",
    "trigger_algo.subtitle": "ML tracking, budget, ROI and explainability of algorithmic scores.",
    "trigger_algo.guide_expander": "📖 How to read this page (artist guide) — open once",
    "trigger_algo.guide_body": (
        "This page answers **one single question**: *\"Will Spotify push my "
        "track on its own through its algorithms?\"* The **first 28 days** after "
        "release (J+28) are decisive — that's the window when the algorithms decide.\n\n"

        "**🎚️ The 3 tracked algorithms**\n"
        "- 💎 **Discover Weekly (DW)** — a weekly personalised playlist sent to listeners "
        "who do NOT know you yet. Pure discovery, the holy grail for winning new fans. "
        "The hardest door to open.\n"
        "- 📡 **Release Radar (RR)** — a weekly playlist pushed to **your followers** on each "
        "release. Easier to trigger (they already follow you), but mostly reaches your "
        "existing audience.\n"
        "- 📻 **Radio** — an \"endless\" algorithmic stream that chains similar tracks. "
        "A sign that Spotify deems you \"reliable\" enough to feed its recommendations. "
        "Demands the most stream volume.\n\n"

        "**🔢 The 2 numbers NOT to confuse**\n"
        "- **DW % / RR % / Radio %** = **absolute and calibrated** trigger probability "
        "(50 % = really a 1-in-2 chance). This is THE measure of your real odds. Decision "
        "bands: 🔴 < 20 % **STOP** · 🟠 20–50 % **OPTIMISE** · 🟢 ≥ 50 % **SCALE**.\n"
        "- **Score /20** = **internal ranking** of your catalogue (best track = 20, "
        "worst = 0). It tells you *which track to push first*, NOT a trigger chance. "
        "A track can be 20/20 with only 10 % real probability.\n\n"

        "**🧭 Key notions**\n"
        "- **Popularity Index (0–100)** — Spotify's \"popularity score\" for the track. It's "
        "the entry door: every algo has a minimum PI. The higher your PI climbs, the more "
        "doors open.\n"
        "- **Elbow thresholds (28d)** — the volume of algo-streams **generated by the playlist "
        "itself** that marks the *start* of a trigger: **~130 (RR)**, **~137 (DW)**, "
        "**~639 (Radio)**. It's the minimum the playlist produces once triggered — "
        "**not** the number of streams you must generate yourself to trigger it.\n"
        "- **Velocity (momentum)** — the recent acceleration speed of streams. A track rising "
        "fast is favoured; a flat track stalls.\n"
        "- **Discovery Mode** — a Spotify option (commission on your royalties) that forces "
        "entry into Radio. Enable/disable depending on context (Algorithm Tracking tab).\n\n"

        "**🗂️ The tabs**\n"
        "- 🎯 **Global View** — track metrics + probabilities + its /20 ranking.\n"
        "- 📊 **Algorithm Tracking** — verdict, action levers, J+28 trajectory, PI doors.\n"
        "- 💰 **Budget & ROI** — how much to spend on ads and when.\n"
        "- 🔍 **Explainability** — *why* the model gives this score (SHAP, levers).\n"
        "- 📈 **Model** — the technical reliability of the ML model.\n"
        "- 📉 **Lifecycle & Benchmark** — where your track stands vs the others, over time.\n\n"

        "⚠️ **Honest limit**: the model predicts WELL *whether* a track will trigger "
        "(classification, AUC ~0.92), but POORLY *how many* streams it will do (volume is "
        "not reliable). **Trust the %, not the € volume forecasts.**"
    ),
    "trigger_algo.no_timeline": "No timeline data available.",
    "trigger_algo.sel_track": "🎵 Track",
    "trigger_algo.sel_period": "📅 Period",
    "trigger_algo.sel_month": "Month",
    "trigger_algo.sel_year": "Year",
    "trigger_algo.sel_custom_range": "Custom range",
    "trigger_algo.tab_global": "🎯 Global View",
    "trigger_algo.tab_algos": "📊 Algorithm Tracking",
    "trigger_algo.tab_budget": "💰 Budget & ROI",
    "trigger_algo.tab_explain": "🔍 Explainability",
    "trigger_algo.tab_model": "📈 Model",
    "trigger_algo.tab_lifecycle": "📉 Lifecycle & Benchmark",

    # _tab_lifecycle.py
    "trigger_algo.lifecycle.caption": (
        "📉 **Maturity & comparison** — where your track stands in its algorithmic "
        "lifecycle (week by week) and how it sits against a reference benchmark. "
        "Useful to tell a \"young\" track from one that's dropping off."
    ),
    "trigger_algo.lifecycle.header": "📉 Algorithmic lifecycle & standardisation",
    "trigger_algo.lifecycle.no_benchmark": (
        "Benchmark unavailable — artefact not generated "
        "(see migration 035 / export_lifecycle_benchmark.py)."
    ),
    "trigger_algo.lifecycle.age_metric": "Track age",
    "trigger_algo.lifecycle.release_caption": (
        "Release: {release} · bracket {bin} · curves = static global cohort"
    ),
    "trigger_algo.lifecycle.notes_expander": "🗒️ Notes & upcoming analyses",
    "trigger_algo.lifecycle.notes_body": (
        "Reserved space for upcoming analyses "
        "(full boxplot distribution, decile segmentation, etc.)."
    ),

    # _tab_model.py
    "trigger_algo.model.caption": (
        "📈 **Under the hood** — the technical reliability of the ML model: classification "
        "accuracy per algo, and a \"predicted vs actual\" comparison. To judge how much "
        "you can trust the probabilities shown in the other tabs."
    ),
    "trigger_algo.model.actual_vs_pred": "📊 Actual vs Predicted — Streams 7d",
    "trigger_algo.model.insufficient_history": (
        "Insufficient history (minimum 2 predictions with streams_7d filled in)."
    ),
    "trigger_algo.model.dw_forecast": "**DW forecast**",
    "trigger_algo.model.dw_frozen": (
        "DW volume not predicted — the DW regressor is frozen (R²<0 in honest "
        "validation, worse than an average). This is **intentional**, not a lack "
        "of data: trust the DW probability, not the volume."
    ),
    "trigger_algo.model.rr_forecast": "**RR forecast**",
    "trigger_algo.model.rr_r2_caption": (
        "⚠️ R²=0.32 — diagnostic only, NOT a forecast. Release Radar volume is "
        "not predictable (noise tied to notification open rate)."
    ),
    "trigger_algo.model.no_rr_pred": "No RR predictions available for this track.",
    "trigger_algo.model.radio_forecast": "**Radio forecast**",
    "trigger_algo.model.no_radio_pred": "No Radio predictions available for this track.",
    "trigger_algo.model.residuals_header": "📉 Residuals over time (Actual − DW Forecast)",
    "trigger_algo.model.no_residuals": (
        "DW residuals unavailable — DW volume is not predicted (regressor frozen "
        "by design). Nothing abnormal for this track."
    ),
    "trigger_algo.model.bias_caption": "Mean bias: {mean:,.0f} streams | Std dev: {std:,.0f} streams",
    "trigger_algo.model.systematic_bias": (
        "Systematic bias detected — the model consistently over- or under-predicts "
        "for this track."
    ),
    "trigger_algo.model.chart_unavailable": "Actual vs Predicted chart unavailable: {err}",

    # _tab_algos.py
    "trigger_algo.algos.caption": (
        "📊 **Tracking & action** — the verdict (STOP / OPTIMISE / SCALE), the concrete "
        "levers to open each algorithmic door, your position on the PI curves, and the "
        "trajectory of the first 28 days vs the real trigger thresholds."
    ),
    "trigger_algo.algos.rr_simulator": "🔮 Release Radar simulator (pre-release) — plan a release",
    "trigger_algo.algos.streams_probas_header": "📈 Streams & algorithmic probabilities",
    "trigger_algo.algos.no_streams_period": "No streams over this period.",
    "trigger_algo.algos.no_ml_history": "No ML probability history over this period.",
    "trigger_algo.algos.chart_streams_probas_title": "Streams & probabilities — {track}",
    "trigger_algo.algos.axis_streams": "Streams",
    "trigger_algo.algos.axis_proba_pi": "Algo proba (%) / Popularity Index",
    "trigger_algo.algos.chart_unavailable": "Streams/probabilities chart unavailable: {err}",
    "trigger_algo.algos.j28_header": "🗓️ J+28 trajectory (since release)",
    "trigger_algo.algos.j28_chart_title": "Trajectory of '{track}' (first 28 days)",
    "trigger_algo.algos.axis_days_since": "Days since release (J+)",
    "trigger_algo.algos.axis_stream_volume": "Stream volume",
    "trigger_algo.algos.axis_popularity": "Popularity (0-100)",
    "trigger_algo.algos.j28_caption": (
        "Curve = the track's cumulative streams over its first 28 days. "
        "ℹ️ **About trigger thresholds:** when an algorithmic playlist fires, it generates "
        "its own volume of algo-streams (28d) that starts around **~130 (RR)**, **~137 (DW)**, "
        "**~639 (Radio)** and settles toward **~417 / ~1,333 / ~8,423** once established. "
        "These are volumes **produced by the playlists** (a detection signal) — **not** a "
        "stream target to reach yourself to trigger them. That's why they aren't drawn as "
        "target lines on your curve."
    ),
    "trigger_algo.algos.projection": "🔮 **Projection:** At this pace → ~**{streams:,.0f} streams** in 28d.",
    "trigger_algo.algos.proj_dw": (
        "🌟 Volume consistent with an emerging Discover Weekly trigger "
        "(at the algo-stream level a playlist emits at its start)."
    ),
    "trigger_algo.algos.proj_rr": (
        "⚠️ At the level of a starting Release Radar trigger; Discover Weekly still short."
    ),
    "trigger_algo.algos.proj_below": "📉 Below the algo-stream level of a starting trigger.",
    "trigger_algo.algos.j28_unavailable": "J+28 trajectory unavailable: {err}",

    # _tab_explainability.py
    "trigger_algo.explain.caption": (
        "🔍 **The why behind the score** — which factors lift or sink each probability "
        "(SHAP charts), and the coach that turns it into concrete action levers. "
        "Red bars = it helps the score, blue = it penalises it."
    ),
    "trigger_algo.explain.no_pred": (
        "No ML prediction available for this track. Run the `ml_scoring_daily` DAG."
    ),
    "trigger_algo.explain.no_features": "features_json missing from the ML prediction.",
    "trigger_algo.explain.parse_failed": "Unable to parse features_json.",
    "trigger_algo.explain.inference_unavailable": "ml_inference unavailable: {err}",
    "trigger_algo.explain.calib_note": "📖 Reading the probabilities (uncalibrated model): {note}",
    "trigger_algo.explain.shap_missing": (
        "`shap` library not installed. Add `shap>=0.44.0` to requirements.txt "
        "then rebuild the Docker image (`docker-compose build && docker-compose up -d`)."
    ),
    "trigger_algo.explain.shap_waterfall": "🔍 SHAP Waterfall — {algo}",
    "trigger_algo.explain.model_not_found": "Model `{key}` not found in machine_learning/mlruns/.",
    "trigger_algo.explain.shap_logodds_caption": (
        "SHAP values in log-odds space (uncalibrated model). "
        "Red bars = positive contribution to the score, blue = negative."
    ),
    "trigger_algo.explain.shap_error": "SHAP {algo}: {err}",
    "trigger_algo.explain.dw_autopsy": "🧾 Autopsy of the predicted VOLUME (DW regressor) — floor",
    "trigger_algo.explain.dw_reg_not_found": "Model `dw_regressor` not found in machine_learning/mlruns/.",
    "trigger_algo.explain.dw_volume_label": "Discover Weekly (volume)",
    "trigger_algo.explain.dw_shap_caption": (
        "SHAP values in 7d streams. Read it as a floor: "
        "the regressor underestimates hits (see badge above)."
    ),
    "trigger_algo.explain.dw_shap_error": "DW regressor SHAP: {err}",
    "trigger_algo.explain.radio_autopsy": "🧾 Autopsy of the predicted Radio VOLUME (regressor) — floor",
    "trigger_algo.explain.radio_reg_not_found": "Model `radio_regressor` not found in machine_learning/mlruns/.",
    "trigger_algo.explain.radio_volume_label": "Radio (volume)",
    "trigger_algo.explain.radio_shap_caption": (
        "SHAP values in 7d streams. Recent fuel dominates; "
        "saves/playlists are flat on volume (see badge)."
    ),
    "trigger_algo.explain.radio_shap_error": "Radio regressor SHAP: {err}",
    "trigger_algo.explain.coach_header": "🧭 Coach & decision sliders per algorithm",

    # _tab_global.py
    "trigger_algo.global.caption": (
        "🎯 **Overview** — the track's key figures over the period, the evolution of "
        "its trigger probabilities, and its /20 rank in your catalogue. Start here."
    ),
    "trigger_algo.global.metrics_header": "📊 Metrics over the selected period",
    "trigger_algo.global.listeners_metric": "Listeners ({win})",
    "trigger_algo.global.listeners_help": "{win} snapshot from s4a_songs_global (source: S4A export)",
    "trigger_algo.global.streams_metric": "Track streams ({win})",
    "trigger_algo.global.saves_metric": "Saves ({win})",
    "trigger_algo.global.saves_help": "{win} snapshot from s4a_songs_global",
    "trigger_algo.global.playlist_adds_metric": "Playlist adds (28d)",
    "trigger_algo.global.playlist_adds_help": "28d snapshot — entered in « 📝 S4A Entry » (Data section)",
    "trigger_algo.global.trigger_trend_header": "🎚️ Trigger rate evolution (selected track)",
    "trigger_algo.global.trigger_trend_caption": (
        "DW / RR / Radio trigger probability of the track over time. "
        "The dashed line at 50 % marks the decision trigger threshold."
    ),
    "trigger_algo.global.no_ml_history": "No ML probability history over this period.",
    "trigger_algo.global.threshold_50": "Trigger threshold 50 %",
    "trigger_algo.global.axis_pred_date": "Prediction date",
    "trigger_algo.global.axis_trigger_proba": "Trigger probability (%)",
    "trigger_algo.global.trigger_curve_unavailable": "Trigger rate curve unavailable: {err}",
    "trigger_algo.global.score20_header": "🏆 Score /20 — Benchmark across all tracks",
    "trigger_algo.global.score20_caption": (
        "⚖️ **Relative** score (a ranking, not a probability): "
        "`0.35·DW + 0.35·RR + 0.20·Radio + 0.10·velocity`, then **min-max** stretched over "
        "the catalogue → the **best track = 20.0, the worst = 0.0**, the rest spread "
        "in between. It's an internal ranking: 20.0 does NOT mean \"100 % trigger chance\", "
        "and 0.0 does NOT mean \"no chance\" (just last in the catalogue). **`Streams 28d` "
        "is not part of the calculation** (a context column). When DW/RR/Radio probabilities "
        "are very close between tracks, it's the **velocity** (recent momentum, 10 % of the "
        "weight) that breaks the tie. For the **absolute** trigger probability, read the "
        "DW % / RR % / Radio % columns (calibrated model outputs), not the score."
    ),
    "trigger_algo.global.no_benchmark_pred": "No ML prediction available for the benchmark.",
    "trigger_algo.global.benchmark_unavailable": "Benchmark score unavailable: {err}",
    "trigger_algo.global.objectives_header": "🎯 Algorithmic Objectives (J+28)",
    "trigger_algo.global.days_elapsed_metric": "Days elapsed (J+28)",
    "trigger_algo.global.days_remaining": "{n} remaining",
    "trigger_algo.global.cumul_streams_metric": "Cumulative streams J+28",

    # _tab_budget_roi.py
    "trigger_algo.roi.caption": (
        "💰 **Budget decision** — which tracks to push first (top-N% by score), your "
        "remaining Meta Ads budget, and the risk-adjusted cost (cost ÷ trigger "
        "probability) = the real € to pay to hope to open an algorithmic door."
    ),
    "trigger_algo.roi.risk_adjusted_header": "**Risk-adjusted cost (cost ÷ trigger probability):**",
    "trigger_algo.roi.ml_proba_unavailable": (
        "ML probabilities unavailable for this track (run `ml_scoring_daily`)."
    ),
    "trigger_algo.roi.adj_cost_help": "Nominal cost {cost:,.2f} € ÷ P={p:.0f}% trigger.",
    "trigger_algo.roi.p_nominal_caption": "P={p:.0f}% · nominal {cost:,.0f} €",
    "trigger_algo.roi.best_bet": (
        "🎯 Best bet: **{label}** — each euro there has the highest chance "
        "of converting into a trigger (adjusted cost {cost:,.0f} €)."
    ),
    "trigger_algo.roi.score_reliability": "🎯 Score reliability: {note}",
    "trigger_algo.roi.meta_budget_header": "💶 Meta Ads Budget",
    "trigger_algo.roi.lifetime_budget_metric": "Lifetime budget allocated",
    "trigger_algo.roi.spent_metric": "Spent (period)",
    "trigger_algo.roi.remaining_metric": "Estimated remaining",
    "trigger_algo.roi.cost_per_stream_metric": "Cost / stream",
    "trigger_algo.roi.budget_per_playlist_header": "**Estimated budget to trigger each playlist:**",
    "trigger_algo.roi.budget_sufficient": "**{label}**\n\n~{seuil:,} streams · {cost:.2f} €\n\n✅ Sufficient budget",
    "trigger_algo.roi.budget_short": "**{label}**\n\n~{seuil:,} streams · {cost:.2f} €\n\n❌ {missing:.2f} € short",
    "trigger_algo.roi.shap_volumes_caption": (
        "SHAP trigger volumes (Class 1) per algo, not rounded 1k/10k figures."
    ),
    "trigger_algo.roi.no_active_campaign": "No active Meta campaign found for this artist.",
    "trigger_algo.roi.meta_budget_unavailable": "Meta budget unavailable: {err}",
    "trigger_algo.roi.organic_scaling_header": "🔊 Organic scaling threshold (DW volume)",
    "trigger_algo.roi.organic_scaling_info": (
        "To trigger the **volume scaling** of Discover Weekly, aim for a base "
        "of at least **~{scale:,} organic streams/28d** (search, profile — excluding "
        "autoplay). Below this threshold, the impact on volume is flat; above it, Spotify "
        "\"opens the floodgates\" and multiplies the throughput."
    ),
    "trigger_algo.roi.organic_scaling_caption": (
        "⚠️ The live organic value (NonAlgoStreams by source) is not yet "
        "collected (Phase 2 — split by S4A source): this threshold is shown as a "
        "**target**, not a gap computed on your data."
    ),
    "trigger_algo.roi.playlist_budget_expander": "💶 Playlist budget — Groover & Fluence",
    "trigger_algo.roi.reference_rates": "Reference rates — check current prices on the platforms.",
    "trigger_algo.roi.budget_simulator": "**Budget simulator**",
    "trigger_algo.roi.total_budget_input": "Total budget (€)",
    "trigger_algo.roi.platform_select": "Platform",
    "trigger_algo.roi.already_spent_input": "Already spent (€)",
    "trigger_algo.roi.remaining_budget_metric": "Remaining budget",
    "trigger_algo.roi.cost_per_submission_metric": "Cost / submission",
    "trigger_algo.roi.possible_submissions_metric": "Possible submissions",
    "trigger_algo.roi.budget_insufficient": "Insufficient budget for one more submission.",
    "trigger_algo.roi.can_submit": "You can still submit to **{n}** curators on {platform}.",
    "trigger_algo.roi.regression_header": "📉 ROI — Linear regression (monthly)",
    "trigger_algo.roi.regression_caption": (
        "Over **all available monthly history** (iMusician revenue × Meta Ads spend), "
        "independently of the period chosen at the top: a monthly regression needs "
        "several months, which a J+28 window cannot provide."
    ),
    "trigger_algo.roi.trace_monthly": "Monthly",
    "trigger_algo.roi.trace_regression": "Regression (R²={r2:.2f})",
    "trigger_algo.roi.regression_chart_title": "iMusician Revenue (€) vs Meta Ads Spend (€)",
    "trigger_algo.roi.axis_meta_spend": "Meta Ads spend (€)",
    "trigger_algo.roi.axis_imusician_revenue": "iMusician revenue (€)",
    "trigger_algo.roi.r2_help": "1.0 = perfect spend↔revenue correlation",
    "trigger_algo.roi.slope_metric": "Slope",
    "trigger_algo.roi.slope_help": "Revenue generated per € invested in Meta Ads",
    "trigger_algo.roi.pvalue_help": "< 0.05 = statistically significant correlation",
    "trigger_algo.roi.insufficient_data": (
        "Insufficient data: at least 2 months are needed where Meta Ads spend "
        "AND iMusician revenue coexist."
    ),
    "trigger_algo.roi.no_revenue_spend": (
        "No revenue/spend data to compute the ROI regression "
        "(no month with Meta Ads spend + iMusician revenue in the history)."
    ),
    "trigger_algo.roi.scipy_unavailable": "scipy unavailable — regression disabled.",
    "trigger_algo.roi.regression_unavailable": "ROI chart unavailable: {err}",
    "trigger_algo.roi.breakeven_header": "⚖️ Breakeven — Cumulative spend vs Cumulative revenue",
    "trigger_algo.roi.trace_cumul_spend": "Cumulative Meta Spend",
    "trigger_algo.roi.trace_cumul_revenue": "Cumulative iMusician Revenue",
    "trigger_algo.roi.trace_popularity": "Popularity (0-100)",
    "trigger_algo.roi.breakeven_annotation": "Breakeven: {date}",
    "trigger_algo.roi.breakeven_reached": "✅ Breakeven reached on **{date}**",
    "trigger_algo.roi.breakeven_not_reached": "⚠️ Breakeven not reached over the available period.",
    "trigger_algo.roi.breakeven_chart_title": "Cumulative Meta spend vs Cumulative iMusician revenue",
    "trigger_algo.roi.axis_cumul_amount": "Cumulative amount (€)",
    "trigger_algo.roi.breakeven_missing_data": "Spend or revenue data missing for the breakeven chart.",
    "trigger_algo.roi.breakeven_unavailable": "Breakeven chart unavailable: {err}",

    # _common.py
    "trigger_algo.common.prob_insufficient": "**{label}** — insufficient data",
    "trigger_algo.common.prob_bar": "**{label}** {badge} — {pct:.0f}%",
    "trigger_algo.common.estimated_volume": "Estimated volume",
    "trigger_algo.common.ml_pred_date": "ML prediction from **{date}** — model `{ver}`",
    "trigger_algo.common.heuristic_mode": (
        "⚠️ **Heuristic Mode** — No ML prediction available. "
        "Run the `ml_scoring_daily` DAG to get ML probabilities."
    ),
    "trigger_algo.common.heur_rr": "**📡 Release Radar** ({pct}%)",
    "trigger_algo.common.trigger_activated": "✅ Trigger theoretically activated!",
    "trigger_algo.common.rr_missing": "{n:,.0f} streams short (rounded heuristic threshold)",
    "trigger_algo.common.heur_dw": "**💎 Discover Weekly** ({pct}%)",
    "trigger_algo.common.dw_streams_pct": "Streams: {pct:.0f}% (goal 10k)",
    "trigger_algo.common.dw_pop_pct": "Popularity: {pct:.0f}% (goal 30)",
    "trigger_algo.common.heur_radio": "**📻 Radio Spotify** ({pct}%)",
    "trigger_algo.common.radio_detected": "✅ 28d streams at the level of a detected Radio trigger.",
    "trigger_algo.common.radio_below": (
        "28d streams ({cur:,.0f}) below the detection level of a "
        "Radio trigger (~{goal:,.0f} algo-streams emitted by the playlist)."
    ),
    "trigger_algo.common.heuristic_thresholds": (
        "ℹ️ The 1k/10k targets are **rounded heuristics**. The elbow thresholds "
        "(~{dw} DW · ~{rr} RR · ~{radio} Radio) are the **minimum algo-streams a "
        "playlist generates** at the start of a trigger — a detection signal, **not** a "
        "stream target to produce yourself to trigger it."
    ),
    "trigger_algo.common.key_factors_header": "🔍 Key factors & marketing levers",
    "trigger_algo.common.strengths_header": "**✅ Strengths**",
    "trigger_algo.common.no_positive": "No positive factor detected.",
    "trigger_algo.common.improve_header": "**⚠️ Areas to improve — recommended actions**",
    "trigger_algo.common.no_negative": "No negative factor detected.",
    "trigger_algo.common.imputation_warning": (
        "⚠️ **{n}/{total} variables imputed to 0/neutral** "
        "for lack of S4A data: the probabilities are **indicative, uncalibrated** "
        "(a relative comparison between tracks, not an absolute probability).\n\n"
        "Variables concerned: {labels}."
    ),
    "trigger_algo.common.dm_unknown": (
        "ℹ️ **Discovery Mode not specified** for this track → treated as "
        "disabled (may skew DW/Radio). Enter it in the "
        "« 🎯 Global View » tab to make the score more reliable."
    ),
    "trigger_algo.common.dm_on": "enabled",
    "trigger_algo.common.dm_off": "disabled",
    "trigger_algo.common.dm_known": "✅ Discovery Mode specified: **{state}** (real data, not imputed).",
    "trigger_algo.common.manual_entered": "✅ S4A entries applied: **{names}** (real data, not imputed).",
    "trigger_algo.common.drift_detected": (
        "📉 **Drift detected**: {n} variable(s) outside the training "
        "envelope (|z| > 4) — {vars}. The prediction extrapolates "
        "and is less reliable for this track."
    ),
    "trigger_algo.common.drift_none": "📉 Drift: all variables are within the training envelope.",
    "trigger_algo.common.pi_gate_header": "🚪 Algorithmic doors by Popularity Index",
    "trigger_algo.common.pi_gate_caption": (
        "The Popularity Index (0-100) is the entry door of each algorithm. "
        "The white bar locates your track; n = sample size per bracket."
    ),
    "trigger_algo.common.pi_tables_unavailable": (
        "PI threshold tables unavailable — run `python3 machine_learning/train.py`."
    ),
    "trigger_algo.common.pi_predicted_metric": "Predicted Popularity Index",
    "trigger_algo.common.pi_predicted_help": (
        "PI regressor (model v3). R²=0.92 [0.88–0.94] validated in "
        "per-song group-CV, MAE ~2 pts — robust (verified 2026-06-05)."
    ),
    "trigger_algo.common.pi_no_pred": "No predicted PI for this track (daily ML scoring not yet run).",
    "trigger_algo.common.pi_chances": (
        "At **PI {here}**, your trigger chances: "
        "Release Radar **{rr}** · Discover Weekly **{dw}** · Radio **{radio}**."
    ),
    "trigger_algo.common.pi_lever1": (
        "🎯 Lever #1 — the Discover Weekly key is at **PI {bracket}** "
        "({prob:.0f}% trigger). Focus organic streams + saves "
        "to push the PI toward that bracket before scaling the budget."
    ),
    "trigger_algo.common.pi_breakeven_header": "**🎯 Profitability driven by the Popularity Index**",
    "trigger_algo.common.pi_breakeven_caption": (
        "Current predicted PI: **{pi} / 100** (bracket {bracket}). You only break even "
        "via an algo if your PI crosses its trigger door."
    ),
    "trigger_algo.common.gate_reached": "✅ door reached",
    "trigger_algo.common.gate_requires": "⛔ requires PI {gate}",
    "trigger_algo.common.gate_line": "- **{label}**: door at PI **{gate}** — {status}",
    "trigger_algo.common.verdict_stop": (
        "🔴 **STOP** — weak algorithmic signals (best lead: "
        "{algo} {prob:.0%}). Stop your Meta Ads on this track "
        "to preserve your budget."
    ),
    "trigger_algo.common.verdict_optimize": (
        "🟠 **OPTIMISE** — potential detected ({algo} {prob:.0%}), "
        "but a trigger is missing."
    ),
    "trigger_algo.common.verdict_lever1": "🎯 Lever #1 — {label}: {lever}",
    "trigger_algo.common.verdict_scale": (
        "🟢 **SCALE** — hit DNA detected ({algo} {prob:.0%}). "
        "The algorithm is ready to take over: raise your daily budget "
        "by ~20 % to maximise the snowball effect."
    ),
    "trigger_algo.common.verdict_reliability": "ℹ️ Score reliability: {note}",
    "trigger_algo.common.verdict_platt": (
        "Calibrated probabilities (Platt) — the 20 %/50 % thresholds map to real "
        "trigger probabilities."
    ),
    "trigger_algo.common.snowball_safe": (
        "🏆 **\"Safe Bet\" Status** — {n} tracks in active algorithmic radio. "
        "Ideal moment to release a new single: it will be pushed more easily."
    ),
    "trigger_algo.common.snowball_warming": (
        "🔥 **Warming up** — {n} track(s) in active radio. Reach 3 tracks to "
        "unlock the algorithmic \"free pass\" on your next releases."
    ),
    "trigger_algo.common.snowball_cold": (
        "❄️ No track in active algorithmic radio (model estimate). "
        "Focus efforts to break through a first track."
    ),
    "trigger_algo.common.snowball_caption": (
        "Snowball effect — model estimate (radio_probability ≥ 0.5), not the "
        "real radio count (data not collected at inference)."
    ),
    "trigger_algo.common.resurrection_header": "✨ Long-tail resurrection",
    "trigger_algo.common.resurrection_none": (
        "No spark detected on your old tracks (> 6 months). The radar "
        "activates once ~2 weeks of saves history accumulate "
        "(automatic daily collection)."
    ),
    "trigger_algo.common.resurrection_spark": (
        "✨ **{song}** ({age} d) — +{gain} recent saves. "
        "Inject a small Ads budget today to wake up the Discover Weekly."
    ),
    "trigger_algo.common.phase_title": "**{title}** · track at J+{days}",
    "trigger_algo.common.feat_imp_expander": "📊 Hierarchy of the 13 variables per algorithm",
    "trigger_algo.common.feat_imp_caption": (
        "Relative weight of each variable in the model's decision "
        "(XGBoost gain — proxy for global SHAP importance)."
    ),
    "trigger_algo.common.dm_protocol_expander": "🎚️ Discovery Mode protocol (activation & kill-switch)",
    "trigger_algo.common.dm_protocol_body": (
        "- **Release Radar (week 1)**: **zero** impact — don't sacrifice 30 % of "
        "your royalties, it's ineffective.\n"
        "- **Radio (month 3+)**: **activation lever** — it forces entry into Radio "
        "(the \"VIP bouncer\"), but does not scale volume.\n"
        "- **Kill-switch**: as soon as a track exceeds **~10,000 streams/day on Radio**, "
        "**disable** Discovery Mode — organic inertia is enough, you recover "
        "your 30 % margin."
    ),
    "trigger_algo.common.dm_protocol_caption": (
        "Live Discovery Mode status not collected (imputed to 0 at inference) — "
        "protocol shown for guidance only."
    ),
    "trigger_algo.common.gate28_header": "**🚪 28-day door — streams & listeners vs per-algo thresholds**",
    "trigger_algo.common.gate28_caption": "This track (28d): **{streams:,} streams** · **{listeners:,} listeners**.",
    "trigger_algo.common.gate28_streams": "{mark} streams ≥ {thr:,}",
    "trigger_algo.common.gate28_listeners": "{mark} listeners ≥ {thr:,}",
    "trigger_algo.common.gate28_note": (
        "Approximate 28d thresholds, derived from data_anon.csv (success-rate knee)."
    ),
    "trigger_algo.common.ar_selector_header": "🎯 A&R selection by budget (top-N%)",
    "trigger_algo.common.ar_selector_min": (
        "Tool available from ≥ 3 scored tracks (catalogue scale). "
        "Run the `ml_scoring_daily` DAG."
    ),
    "trigger_algo.common.ar_slider": "Push the top N% by score",
    "trigger_algo.common.ar_slider_help": (
        "Low threshold → high precision (little waste); high threshold → high recall."
    ),
    "trigger_algo.common.ar_selected_metric": "Tracks selected",
    "trigger_algo.common.ar_precision_metric": "Model precision",
    "trigger_algo.common.ar_lift_metric": "Lift top-10%",
    "trigger_algo.common.ar_recall_metric": "Recall",
    "trigger_algo.common.ar_caption": (
        "Tight budget → aim for the top 10% (near-perfect precision, little waste). "
        "Large budget → lower the threshold to capture more opportunities (recall ↑, precision ↓)."
    ),
    "trigger_algo.common.ar_col_track": "Track to push",
    "trigger_algo.common.ar_col_score": "Score /20",
    "trigger_algo.common.velocity_advice": (
        "⚡ High velocity ({vel:.2f}) on « {track} » — Radio (threshold {radio:g}) "
        "and DW ({dw:g}) penalise hyper-growth (\"flash in the pan\"). Suggestion: "
        "cut spend by ~30 % ({spent:,.0f} € → {reduced:,.0f} €) to smooth the traffic."
    ),
    "trigger_algo.common.pacing_header": "📅 Budget smoother (Pacing)",
    "trigger_algo.common.pacing_budget_input": "Budget to spread (€)",
    "trigger_algo.common.pacing_window_input": "Smoothing window (days)",
    "trigger_algo.common.pacing_window_help": "28 d = algo evaluation window.",
    "trigger_algo.common.pacing_daily_metric": "Recommended daily spend",
    "trigger_algo.common.pacing_penalty_threshold": "the penalty threshold",
    "trigger_algo.common.pacing_info": (
        "Spread **{budget:,.0f} €** over **{window} days** (~{per_day:,.0f} €/day) to "
        "maintain organic growth and avoid the \"suspicious spike\" that Discover "
        "Weekly penalises (velocity beyond {vtxt})."
    ),
    "trigger_algo.common.pacing_burn_warning": (
        "⚠️ Your current daily budget (~{daily:,.0f} €/day) would burn "
        "this budget in ~{burn:.0f} days → velocity-spike risk. "
        "Reduce to ~{per_day:,.0f} €/day."
    ),
    "trigger_algo.common.pacing_caption": (
        "The €→velocity link is a smoothing heuristic (spread over the eval "
        "window), not a guaranteed target velocity."
    ),
    "trigger_algo.common.meta_lever_header": "**🎯 Marketing levers — real Meta Ads performance of this track**",
    "trigger_algo.common.meta_lever_unavailable": "Meta data unavailable: {err}",
    "trigger_algo.common.meta_lever_no_campaign": (
        "No Meta campaign mapped to this track — map them in the "
        "« Meta ↔ Spotify » view to score your levers on real performance."
    ),
    "trigger_algo.common.meta_col_campaign": "Campaign",
    "trigger_algo.common.meta_col_clicks": "Clicks",
    "trigger_algo.common.meta_best_lever": "✅ Best lever: **{name}** — CPR {cpr:.3f} € ({cta})",
    "trigger_algo.common.cta_na": "CTA n/a",
    "trigger_algo.common.meta_worst_lever": (
        "⚠️ Less effective: **{name}** — CPR {cpr:.3f} € "
        "→ reallocate toward the CTA/audience that performs."
    ),
    "trigger_algo.common.meta_cpr_caption": (
        "CPR = cost per result (lower = better). Cross-check with the penalised SHAP "
        "lever: the « Add to playlist » CTA beats « Listen » on DW."
    ),
    "trigger_algo.common.lime_expander": "🍋 Local LIME explanation — Discover Weekly",
    "trigger_algo.common.lime_caption": (
        "Local contribution of each condition to the DW probability "
        "(complements the SHAP waterfall — a perturbation-based view)."
    ),
    "trigger_algo.common.lime_not_installed": "`lime` module not installed — `pip install lime`.",
    "trigger_algo.common.lime_unavailable": "LIME unavailable: {err}",
    "trigger_algo.common.band_p25_p75": "P25–P75 (cohort)",
    "trigger_algo.common.band_median": "Cohort median",
    "trigger_algo.common.band_category_avg": "Category average (1.0×)",
    "trigger_algo.common.band_this_track": "This track",
    "trigger_algo.common.band_chart_title": "{algo} — standardisation ratio by age",
    "trigger_algo.common.band_axis_age": "Track age (weeks)",
    "trigger_algo.common.band_axis_ratio": "Ratio (track / category average)",
    "trigger_algo.common.std_position_header": "#### 📍 This track's position vs cohort",
    "trigger_algo.common.std_unknown_release": "Unknown release date — cannot locate the track.",
    "trigger_algo.common.std_no_cohort_ref": (
        "Age: **{age} wk** (bracket {bin}). Cohort total-streams reference "
        "unavailable (provisional artefact) — only the age is "
        "overlaid on the curves above."
    ),
    "trigger_algo.common.std_no_streams": "Track streams unavailable.",
    "trigger_algo.common.std_position_metric": "Position vs cohort (bracket {bin})",
    "trigger_algo.common.std_vs_median": "{pct:+.0f}% vs median",
    "trigger_algo.common.std_ratio_caption": (
        "Ratio based on the **total** streams (all sources, 28d). The "
        "per-algorithm breakdown comes from the global cohort and is NOT "
        "measured on this track."
    ),
    "trigger_algo.common.legend_expander": "ℹ️ Understanding the lifecycle curves & standardisation",
    "trigger_algo.common.legend_body": (
        "**Standardisation ratio**: compares this track's streams to the average "
        "of tracks in the same *weight category* (follower decile for DW/RR, "
        "popularity bucket for Radio). **1.0× = average**, >1.0× = "
        "above, <1.0× = below. The ratio is on the **total** streams; "
        "the per-algorithm split comes from the global cohort.\n\n"
        "**Lifecycle phases:**\n"
        "- 🕳️ **Valley of death** (Radio, wk 5-10): algorithmic trough after the initial push.\n"
        "- 📈 **Resurrection** (Radio, wk 25-100+): long-tail recovery if engagement holds.\n"
        "- 🧗 **Cliff** (Release Radar, after wk 5-6): RR targets newness, exposure drops fast.\n"
        "- ♾️ **No expiry** (Discover Weekly): DW can re-expose a track durably.\n\n"
        "Curves = P25-P75 band + median of a **global** cohort (static). "
        "White vertical line = your track's current age."
    ),

    # ── Feature display labels (rendered via ml_widgets.label_text) ────────────
    # algo-independent: keyed by fid only — slug: algo.label.<fid>.
    # Source FR strings live in algo_knowledge.py (ALGO_FEATURE_ZONES/ALGO_VOLUME_ZONES).
    "algo.label.StreamsLast7Days": "7-day streams",
    "algo.label.CurrentSpotifyFollowers": "Spotify followers",
    "algo.label.HowManySongsHasThisArtistEverReleased": "Catalogue size",
    "algo.label.DaysSinceRelease": "Track age",
    "algo.label.ListenersStreamRatio28Days": "Plays / listener (28d)",
    "algo.label.Velocity_Streams": "Velocity",
    "algo.label.ReleasePhaseEarly": "Release phase",
    "algo.label.ReleaseConsistencyNum": "Release cadence",
    "algo.label.HowManySongsDoYouHaveInRadioRightNow": "Tracks in Radio",
    "algo.label.IsThisSongOptedIntoSpotifyDiscoveryMode": "Discovery Mode",
    "algo.label.NonAlgoStreams28Days": "Non-algo streams (28d)",
    "algo.label.SavesLast28Days": "Saves (28d)",
    "algo.label.PlaylistAddsLast28Days": "Playlist adds (28d)",
    # SHAP-narrative / key-factor labels (_FEATURE_LABELS, suffixed keys) —
    # slug: algo.label.<col>. FR source lives in trigger_algo/_common.py.
    # Keys without _log/_adj suffix collide with the fid labels above (same
    # feature, one EN value serves both contexts) — only the distinct ones below.
    "algo.label.StreamsLast7Days_log": "7-day streams",
    "algo.label.CurrentSpotifyFollowers_log": "Spotify followers",
    "algo.label.ListenersStreamRatio28Days_adj": "Listener/stream ratio (loyalty)",
    "algo.label.NonAlgoStreams28Days_log": "Non-algo streams (28d)",
    "algo.label.SavesLast28Days_adj": "Saves (28d)",
    "algo.label.PlaylistAddsLast28Days_adj": "Playlist adds (28d)",

    # ── algo_knowledge coaching prose (rendered via ml_widgets resolvers) ──────
    # Entry/classification levers (ALGO_FEATURE_ZONES) — slug:
    # algo.lever.entry.<ALGO>.<feature>. FR source lives inline in algo_knowledge.py.
    "algo.lever.entry.DW.StreamsLast7Days": (
        "The first euro to cross ~1,000→2,000 streams/7d is the most cost-effective; "
        "beyond 2,500 the marginal impact fades."
    ),
    "algo.lever.entry.DW.NonAlgoStreams28Days": (
        "Generate ≥ ~3,900 active organic streams/28d (search, profile) — autoplay "
        "doesn't count (empirical knee)."
    ),
    "algo.lever.entry.DW.DaysSinceRelease":
        "Get past the 60-day mark: the DW golden age runs from ~2 months → 1 year.",
    "algo.lever.entry.DW.Velocity_Streams": (
        "Growth of 1.2-2.0 is ideal and unpenalised; only a spike > 3.5 (sudden volume, "
        "suspected bots) triggers a malus."
    ),
    "algo.lever.entry.DW.CurrentSpotifyFollowers": (
        "The tipping threshold is ~1,000 followers; the real authority bonus only "
        "kicks in at ~2,650 (empirical knee)."
    ),
    "algo.lever.entry.DW.HowManySongsDoYouHaveInRadioRightNow":
        "Having ≥ 9 tracks in Radio rotation grants a momentum bonus.",
    "algo.lever.entry.DW.ListenersStreamRatio28Days":
        "Get past ~1.6 streams/listener; beyond 4 the ratio becomes suspect.",
    "algo.lever.entry.DW.SavesLast28Days": (
        "Aim for ≥ ~165 saves/28d: that's where the DW impact turns clearly positive "
        "(empirical knee, not the over-hyped figure of 500)."
    ),
    "algo.lever.entry.DW.PlaylistAddsLast28Days": (
        "Get past ~175 user playlist adds/28d — the strongest intent signal for DW."
    ),
    "algo.lever.entry.DW.ReleaseConsistencyNum": (
        "Space your releases at least ~6 weeks apart (ideally up to 14) so you don't "
        "cannibalise the velocity of the previous one."
    ),
    "algo.lever.entry.DW.HowManySongsHasThisArtistEverReleased":
        "Better 10 tracks worked hard than 50 lying dormant.",
    "algo.lever.entry.DW.IsThisSongOptedIntoSpotifyDiscoveryMode":
        "Discovery Mode: a slight edge but a microscopic impact.",
    "algo.lever.entry.DW.ReleasePhaseEarly": (
        "In the first 4-5 weeks, DW applies a probation malus; it's the Release Radar "
        "that carries you at this stage."
    ),
    "algo.lever.entry.RR.DaysSinceRelease": (
        "RR only fires within the ~7→40 day window: it's a time gate, not a lever. "
        "Concentrate all the effort on that slot."
    ),
    "algo.lever.entry.RR.StreamsLast7Days": (
        "Generate ≥ 2,000 streams during release week (Meta Ads « Traffic » on Friday): "
        "it's the impulse that fires RR at full throttle."
    ),
    "algo.lever.entry.RR.CurrentSpotifyFollowers": (
        "RR is a notification to followers: convert ≥ 2,300 followers so Spotify is "
        "forced to trigger the send."
    ),
    "algo.lever.entry.RR.ReleaseConsistencyNum": (
        "Space your releases (~14 wk): each track then gets a full RR notification "
        "window instead of cannibalising itself."
    ),
    "algo.lever.entry.RR.IsThisSongOptedIntoSpotifyDiscoveryMode": (
        "SHAP flat at zero: Discovery Mode has NO impact on RR. Don't sacrifice 30% of "
        "royalties in week 1 — enable it in month 2 for Radio."
    ),
    "algo.lever.entry.RR.PlaylistAddsLast28Days":
        "Ignore this signal for RR: it measures age, not engagement.",
    "algo.lever.entry.RADIO.StreamsLast7Days": (
        "Cross ~2,000 streams/7d (critical threshold) — beyond that, a guaranteed Radio "
        "entry ticket."
    ),
    "algo.lever.entry.RADIO.Velocity_Streams": (
        "Radio hates hyper-growth: keep velocity < 1.5 (ideal 0.5-1.2). A spike = "
        "blacklist. Smooth the traffic."
    ),
    "algo.lever.entry.RADIO.NonAlgoStreams28Days": (
        "Bring in ≥ 2,000 organic streams/28d: Radio relays real demand, it doesn't "
        "create it."
    ),
    "algo.lever.entry.RADIO.CurrentSpotifyFollowers":
        "Reach 2,000 followers — Radio safety cap.",
    "algo.lever.entry.RADIO.HowManySongsDoYouHaveInRadioRightNow": (
        "Getting a single track into Radio unlocks a trust bonus on every subsequent "
        "release."
    ),
    "algo.lever.entry.RADIO.HowManySongsHasThisArtistEverReleased":
        "Aim for 10-20 tracks in the catalogue — Radio trust peak.",
    "algo.lever.entry.RADIO.DaysSinceRelease": (
        "Radio removes the newness bonus after ~50d but doesn't kill you: with good "
        "retention, it plays you for years."
    ),
    "algo.lever.entry.RADIO.IsThisSongOptedIntoSpotifyDiscoveryMode": (
        "Ticking Discovery Mode (Spotify for Artists, −30% royalties) almost forces "
        "the Radio door open."
    ),
    "algo.lever.entry.RADIO.SavesLast28Days": (
        "Increase saves (retention) — Radio rewards loyalty over the long run."
    ),
    "algo.divnote.RR.PlaylistAddsLast28Days": (
        "Misleading negative SHAP: tracks with high adds are already old (3-4 wk) and "
        "outside the RR window — it's a proxy for age, not a lever. Above all, don't "
        "cut your playlist adds."
    ),

    # Volume/regressor levers (ALGO_VOLUME_ZONES) — slug: algo.lever.vol.<ALGO>.<feature>.
    "algo.lever.vol.DW.StreamsLast7Days": (
        "Cross ~6,000 streams over 7 days: beyond that, DW adds a vertical bonus of "
        "+400 to +800 streams to the predicted volume (spark effect)."
    ),
    "algo.lever.vol.DW.NonAlgoStreams28Days": (
        "Bring in 6,000–10,000 active organic streams/28d (search, profile — autoplay "
        "doesn't count): it's the #1 multiplier of DW volume."
    ),
    "algo.lever.vol.DW.SavesLast28Days": (
        "Saves buy the ENTRY into DW (classification) but don't increase the VOLUME "
        "once inside: don't over-invest here to scale."
    ),
    "algo.lever.vol.DW.PlaylistAddsLast28Days": (
        "Like saves: an entry lever, not a volume one. DW throughput comes from organic "
        "fuel, not playlist adds."
    ),
    "algo.lever.vol.RADIO.StreamsLast7Days": (
        "Radio VOLUME is driven by recent fuel (dominant SHAP): inject external traffic "
        "to cross cruising velocity (~10,000 streams/day). Beyond that, the algo "
        "amplifies massively. Provisional thresholds (qualitative SHAP, ~300 tracks)."
    ),
    "algo.lever.vol.RADIO.HowManySongsDoYouHaveInRadioRightNow": (
        "The only NON-flat catalogue feature for volume: the more tracks you have active "
        "in Radio, the more Spotify over-distributes the next ones (artist trust score). "
        "Build a steady Radio catalogue."
    ),
    "algo.lever.vol.RADIO.IsThisSongOptedIntoSpotifyDiscoveryMode": (
        "PARADOX: Discovery Mode almost guarantees ENTRY into Radio (classification) but "
        "is SHAP-flat at zero on VOLUME. Once at cruising velocity, turn it off to "
        "recover 30% of royalties — the algo keeps pushing via your organic velocity."
    ),
    "algo.lever.vol.RADIO.SavesLast28Days": (
        "Saves buy the ENTRY into Radio (classification) but don't increase the VOLUME "
        "broadcast: don't over-invest here to scale throughput."
    ),
    "algo.lever.vol.RADIO.PlaylistAddsLast28Days": (
        "Like saves: an entry lever, not a volume one. Radio throughput comes from "
        "recent fuel, not playlist adds."
    ),
    "algo.lever.vol.RADIO.ListenersStreamRatio28Days": (
        "The replay ratio proves quality at entry but stays flat on VOLUME: it doesn't "
        "multiply the number of streams broadcast."
    ),

    # Radio margin-recovery note (cruising-velocity Discovery Mode) — interpolated.
    "algo.recovery.radio": (
        "💸 Cruising velocity reached (~{val:,.0f} streams/7d ≥ {target:,.0f}). "
        "If Discovery Mode is enabled on this track, turn it off: it has done its Radio "
        "entry job but adds no volume (SHAP flat at zero). You recover ~30% of "
        "royalties — the algo keeps pushing via your organic velocity."
    ),

    # Volume-regressor interpretation (hungry-model badge) — slug: algo.regressor.<ALGO>.
    "algo.regressor.DW": (
        "DW volume regressor NOT reliable: R²<0 in group-CV (the volume target is "
        "dominated by a few viral outliers). Volume hidden from user surfaces; kept as "
        "a diagnostic only. Classification, however, stays solid."
    ),
    "algo.regressor.RADIO": (
        "The least-bad Radio regressor of the three (R²=0.33 in honest per-song "
        "validation, log target) but still weak: read it as a FLOOR of cruising volume, "
        "never a ceiling. External surges (TikTok, sync) are out-of-model. v1 showed "
        "R²=0.63 — that was a leaked random-split mirage."
    ),
    "algo.regressor.RR": (
        "Release Radar regressor NOT reliable (R²=0.23 in honest validation): it hunts "
        "for logic in noise. Broken by 2-3 viral outliers. Volume hidden from user "
        "surfaces to avoid false financial promises; kept here as a diagnostic only."
    ),

    # 'Forecast suppressed' captions — slug: algo.suppressed.<ALGO>.
    "algo.suppressed.DW": (
        "Flag raised ✅ — but Discover Weekly VOLUME is not predictable (R²<0 in honest "
        "validation: worse than a plain average). We rely on classification (AUC 0.92) "
        "and the levers (saves, playlist-adds), not on a stream forecast."
    ),
    "algo.suppressed.RR": (
        "Followers notified ✅ — Release Radar volume is NOT predictable (R²=0.23 in "
        "honest validation): it depends on the notification open rate (a human factor), "
        "not the algorithm. We rely on classification (AUC 0.94), not a streams/€ forecast."
    ),

    # Classification-scorecard interpretation — slug: algo.model.<ALGO>.
    "algo.model.DW": (
        "AUC 0.917 [0.85–0.98] in honest per-song validation. Discover Weekly is a "
        "LEVERS model: without looking at streams, its performance nearly holds "
        "(AUC 0.91) — the signal comes from Saves and PlaylistAdds. Pushing saves "
        "therefore really moves the DW odds (the marketing framing is justified). "
        "When it raises the flag it's right ~7 times out of 10 (precision 73%) and "
        "captures 64% of hits. Wide confidence band: N=508, read ±0.06 on the AUC."
    ),
    "algo.model.RR": (
        "AUC 0.936 [0.90–0.98] — and above all a REAL forecast: Release Radar stays at "
        "AUC 0.92 from release metadata alone (age, artist size), with no streams at "
        "all. You can therefore announce the RR odds on release day, before a single "
        "listen — it's a planning tool. Top-decile lift ×4.6: investing in Meta Ads on "
        "its predictions multiplies the ROI."
    ),
    "algo.model.RADIO": (
        "AUC 0.925 [0.88–0.97], balanced base (47% hits) → AP 0.92 very high. BUT Radio "
        "is a momentum DIAGNOSTIC, not a forecast: stripped of recent streams, its "
        "performance collapses (AUC 0.93 → 0.77). Read it as « this track is playing "
        "strong right now », not « this track will break out ». Errors ~symmetric."
    ),

    # Calibration bands — slug: algo.calib.<ALGO>.<lower_bound×100>.
    "algo.calib.DW.0": "Reliable: score ≈ reality (observed success ~7%, n=384).",
    "algo.calib.DW.20": "Reliable: score ≈ reality (observed success ~35%, n=23).",
    "algo.calib.DW.40":
        "Underestimated: real success ~69% (better than the displayed score).",
    "algo.calib.DW.60": "Reliable: score ≈ reality (observed success ~66%, n=59).",
    "algo.calib.DW.80": "Reliable: score ≈ reality (observed success ~92%, n=13).",
    "algo.calib.RR.0": "Reliable: score ≈ reality (observed success ~7%, n=395).",
    "algo.calib.RR.20": "Reliable: score ≈ reality (observed success ~30%, n=20).",
    "algo.calib.RR.40": "Reliable: score ≈ reality (observed success ~50%, n=26).",
    "algo.calib.RR.60": "Reliable: score ≈ reality (observed success ~71%, n=41).",
    "algo.calib.RR.80": "Reliable: score ≈ reality (observed success ~96%, n=26).",
    "algo.calib.RADIO.0": "Reliable: score ≈ reality (observed success ~6%, n=209).",
    "algo.calib.RADIO.20":
        "Underestimated: real success ~55% (better than the displayed score).",
    "algo.calib.RADIO.40": "Reliable: score ≈ reality (observed success ~56%, n=27).",
    "algo.calib.RADIO.60": "Reliable: score ≈ reality (observed success ~59%, n=51).",
    "algo.calib.RADIO.80": "Reliable: score ≈ reality (observed success ~90%, n=168).",

    # Forecast-floor disclaimer — slug: algo.disclaimer.floor.
    "algo.disclaimer.floor": (
        "Estimate = **guaranteed floor** (worst-case). The model underestimates hits: "
        "the real potential is often much higher if it catches fire."
    ),
}
